apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dotnet-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-dotnet-api
  template:
    metadata:
      labels:
        app: todo-dotnet-api
    spec:
      containers:
      - name: api
        image: yousefzydan123/todo-dotnet-api:1.0     
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
          